# Generated by Django 6.1 on 2026-08-20 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.CharField(help_text='Learning dimension this question measures, e.g. "Analytical Thinking"', max_length=100)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('likert', 'Likert Scale'), ('multiple_choice', 'Multiple Choice')], max_length=20)),
                ('options', models.JSONField(blank=True, help_text='For multiple_choice: list of option strings. Null for likert.', null=True)),
                ('display_order', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='LearningProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archetype', models.CharField(max_length=100)),
                ('dimension_scores', models.JSONField()),
                ('strengths', models.JSONField()),
                ('challenges', models.JSONField()),
                ('recommendations', models.JSONField()),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_value', models.JSONField(help_text='Numeric (1-5) for likert, or selected option string for multiple_choice.')),
                ('answered_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='assessment.assessmentquestion')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['question__display_order'],
                'constraints': [models.UniqueConstraint(fields=('student', 'question'), name='unique_student_question')],
            },
        ),
    ]
