# Generated by Django 6.0.4 on 2026-08-20 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('goal', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('daily_minutes', models.PositiveIntegerField(help_text='Maximum study minutes per day.')),
                ('available_days', models.JSONField(default=list, help_text='List of weekday ints (0=Monday..6=Sunday) the student can study.')),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=20)),
                ('teacher_instructions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('ai_generated', models.BooleanField(default=False)),
                ('prompt_version', models.CharField(blank=True, max_length=50)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_plans', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_study_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanAdaptationDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_instructions', models.TextField(blank=True)),
                ('proposed_tasks', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('applied', 'Applied'), ('discarded', 'Discarded')], default='pending_review', max_length=20)),
                ('prompt_version', models.CharField(blank=True, max_length=50)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('study_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adaptation_drafts', to='study_plans.studyplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('estimated_minutes', models.PositiveIntegerField()),
                ('task_type', models.CharField(choices=[('learning', 'Learning'), ('practice', 'Practice'), ('revision', 'Revision'), ('quiz', 'Quiz'), ('reflection', 'Reflection'), ('review', 'Review'), ('assessment', 'Assessment')], max_length=20)),
                ('difficulty', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('order', models.PositiveIntegerField(default=1)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('study_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='study_plans.studyplan')),
            ],
            options={
                'ordering': ['date', 'order'],
            },
        ),
        migrations.CreateModel(
            name='StudyResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('resource_type', models.CharField(choices=[('video', 'Video'), ('article', 'Article'), ('document', 'Document'), ('link', 'Link'), ('exercise', 'Exercise')], max_length=20)),
                ('url', models.URLField(blank=True)),
                ('study_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='study_plans.studytask')),
            ],
        ),
        migrations.AddIndex(
            model_name='studyplan',
            index=models.Index(fields=['student'], name='study_plans_student_03aa15_idx'),
        ),
        migrations.AddIndex(
            model_name='studyplan',
            index=models.Index(fields=['teacher'], name='study_plans_teacher_eda019_idx'),
        ),
        migrations.AddIndex(
            model_name='studytask',
            index=models.Index(fields=['study_plan', 'date'], name='study_plans_study_p_6c276c_idx'),
        ),
    ]
