# Generated by Django 6.0.4 on 2026-08-20 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreeningQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('grade_8_10', 'Grade 8-10'), ('grade_10_12', 'Grade 10-12'), ('undergraduate', 'Undergraduate'), ('postgraduate', 'Postgraduate')], max_length=20)),
                ('section', models.CharField(choices=[('subject_knowledge', 'Subject Knowledge'), ('cognitive_aptitude', 'Cognitive Aptitude'), ('learning_style', 'Learning Style')], max_length=20)),
                ('topic', models.CharField(blank=True, help_text='e.g. "Reading Comprehension". Blank for learning_style.', max_length=100)),
                ('difficulty', models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], help_text='Blank for learning_style probes (non-adaptive).', max_length=10)),
                ('passage', models.TextField(blank=True, help_text='Optional reading passage shown above the question.')),
                ('question_text', models.TextField()),
                ('options', models.JSONField()),
                ('correct_option', models.CharField(blank=True, help_text='A/B/C/D. Blank for learning_style probes (not scored).', max_length=1)),
                ('display_order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['tier', 'section', 'topic', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='SelfReportQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('personality', 'Personality'), ('interests', 'Interests & Career Inclination'), ('wellbeing', 'Wellbeing & Motivation'), ('soft_skills', 'Soft Skills & Behavior'), ('open_message', 'Open Message to Teacher')], max_length=20)),
                ('sub_key', models.CharField(blank=True, help_text='Stable key for this sub-question, e.g. "confidence", "deadlines" — used to key tags in the report.', max_length=50)),
                ('tiers', models.JSONField(blank=True, default=list, help_text='Tier codes this question applies to. Empty = all tiers.')),
                ('question_text', models.TextField()),
                ('options', models.JSONField(blank=True, default=list, help_text='[{"label": "A", "text": "...", "tag": "Achiever"}, ...]. Empty for open-text questions.')),
                ('is_open_text', models.BooleanField(default=False)),
                ('teacher_facing_only', models.BooleanField(default=False, help_text='If true, this response/derived flag is shown only to teachers, never to the student or any aggregate view.')),
                ('display_order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['category', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='ScreeningAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('grade_8_10', 'Grade 8-10'), ('grade_10_12', 'Grade 10-12'), ('undergraduate', 'Undergraduate'), ('postgraduate', 'Postgraduate')], max_length=20)),
                ('part1_status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('part2_status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ScreeningReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_knowledge_score', models.PositiveIntegerField(default=0)),
                ('cognitive_aptitude_score', models.PositiveIntegerField(default=0)),
                ('personality_tag', models.CharField(blank=True, max_length=50)),
                ('interest_tag', models.CharField(blank=True, max_length=50)),
                ('learning_style_tag', models.CharField(blank=True, max_length=50)),
                ('wellbeing_flag', models.CharField(blank=True, max_length=10)),
                ('soft_skills_tags', models.JSONField(blank=True, default=dict)),
                ('open_message', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='screening.screeningattempt')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScreeningResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(max_length=1)),
                ('is_correct', models.BooleanField(blank=True, help_text='Null for non-scored learning_style probes.', null=True)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='screening.screeningattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='screening.screeningquestion')),
            ],
            options={
                'ordering': ['answered_at'],
                'constraints': [models.UniqueConstraint(fields=('attempt', 'question'), name='unique_attempt_question_response')],
            },
        ),
        migrations.CreateModel(
            name='SelfReportResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(blank=True, max_length=1)),
                ('free_text', models.TextField(blank=True)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_report_responses', to='screening.screeningattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='screening.selfreportquestion')),
            ],
            options={
                'ordering': ['answered_at'],
                'constraints': [models.UniqueConstraint(fields=('attempt', 'question'), name='unique_attempt_self_report_question')],
            },
        ),
    ]
