# Generated by Django 6.0.4 on 2026-08-20 21:30

import classroom.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='class',
            name='grade',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='class',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='class',
            name='section',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='class',
            name='subject',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='class',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_code',
            field=models.CharField(db_index=True, default=classroom.models.generate_unique_class_code, max_length=10, unique=True),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['teacher'], name='classroom_c_teacher_398211_idx'),
        ),
    ]
