# Generated by Django 6.0.4 on 2026-08-20 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overview', models.TextField(blank=True)),
                ('learning_preferences', models.JSONField(blank=True, default=list)),
                ('strength_insights', models.JSONField(blank=True, default=list)),
                ('development_insights', models.JSONField(blank=True, default=list)),
                ('teaching_strategies', models.JSONField(blank=True, default=list)),
                ('communication', models.JSONField(blank=True, default=list)),
                ('classroom_recommendations', models.JSONField(blank=True, default=list)),
                ('potential_challenges', models.JSONField(blank=True, default=list)),
                ('teacher_actions', models.JSONField(blank=True, default=list)),
                ('source_profile_snapshot', models.CharField(blank=True, max_length=64)),
                ('prompt_version', models.CharField(blank=True, max_length=50)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('generating', 'Generating'), ('failed', 'Failed')], default='generating', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insight', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAIInsightHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overview', models.TextField(blank=True)),
                ('learning_preferences', models.JSONField(blank=True, default=list)),
                ('strength_insights', models.JSONField(blank=True, default=list)),
                ('development_insights', models.JSONField(blank=True, default=list)),
                ('teaching_strategies', models.JSONField(blank=True, default=list)),
                ('communication', models.JSONField(blank=True, default=list)),
                ('classroom_recommendations', models.JSONField(blank=True, default=list)),
                ('potential_challenges', models.JSONField(blank=True, default=list)),
                ('teacher_actions', models.JSONField(blank=True, default=list)),
                ('prompt_version', models.CharField(blank=True, max_length=50)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insight_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Student AI insight history',
                'ordering': ['-archived_at'],
            },
        ),
    ]
